[package]
name = "virtual_memory_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
indicatif = "0.17.7"
linked-hash-map = "0.5.6"
